Thu Feb 12 23:37:33 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<NoMethodError: undefined method `find_or_create_by_name' for Domain>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'RBRuntime' not found>
#<NoMethodError: undefined method `find_or_create_by_name' for Domain>
#<NameError: uninitialized constant Domain>
#<NameError: uninitialized constant FileImporterWorker::Domain>
#<NameError: uninitialized constant Subscriber>
#<NameError: uninitialized constant FileImporterWorker::Subscriber>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'NSBundle' not found>
#<NameError: NameError>
#<NameError: NameError>
#<LoadError: C constant 'NSProxy' not found>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::CoreImageProcessor>
#<MissingSourceFile: no such file to load -- gd2>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::Gd2Processor>
#<MissingSourceFile: no such file to load -- mini_magick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::MiniMagickProcessor>
#<MissingSourceFile: no such file to load -- RMagick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::RmagickProcessor>
#<MissingSourceFile: no such file to load -- image_science>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::ImageScienceProcessor>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends::FileSystemBackend>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends>
#<NameError: uninitialized constant ImportedFile>
#<NameError: uninitialized constant FileImporterWorker::ImportedFile>
#<NameError: uninitialized constant FileImporterWorker>
#<MissingSourceFile: no such file to load -- sqlite3>
Thu Feb 12 23:42:34 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:08:04 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:14:42 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<NoMethodError: undefined method `find_or_create_by_name' for Domain>
#<NameError: uninitialized constant Domain>
#<NameError: uninitialized constant FileImporterWorker::Domain>
#<NameError: uninitialized constant Subscriber>
#<NameError: uninitialized constant FileImporterWorker::Subscriber>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'NSBundle' not found>
#<NameError: NameError>
#<NameError: NameError>
#<LoadError: C constant 'NSProxy' not found>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::CoreImageProcessor>
#<MissingSourceFile: no such file to load -- gd2>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::Gd2Processor>
#<MissingSourceFile: no such file to load -- mini_magick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::MiniMagickProcessor>
#<MissingSourceFile: no such file to load -- RMagick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::RmagickProcessor>
#<MissingSourceFile: no such file to load -- image_science>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::ImageScienceProcessor>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends::FileSystemBackend>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends>
#<NameError: uninitialized constant ImportedFile>
#<NameError: uninitialized constant FileImporterWorker::ImportedFile>
#<NameError: uninitialized constant FileImporterWorker>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:18:46 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<NoMethodError: undefined method `find_or_create_by_name' for Domain>
#<NameError: uninitialized constant Domain>
#<NameError: uninitialized constant FileImporterWorker::Domain>
#<NameError: uninitialized constant Subscriber>
#<NameError: uninitialized constant FileImporterWorker::Subscriber>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'NSBundle' not found>
#<NameError: NameError>
#<NameError: NameError>
#<LoadError: C constant 'NSProxy' not found>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::CoreImageProcessor>
#<MissingSourceFile: no such file to load -- gd2>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::Gd2Processor>
#<MissingSourceFile: no such file to load -- mini_magick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::MiniMagickProcessor>
#<MissingSourceFile: no such file to load -- RMagick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::RmagickProcessor>
#<MissingSourceFile: no such file to load -- image_science>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::ImageScienceProcessor>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends::FileSystemBackend>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends>
#<NameError: uninitialized constant ImportedFile>
#<NameError: uninitialized constant FileImporterWorker::ImportedFile>
#<NameError: uninitialized constant FileImporterWorker>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:22:37 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<NoMethodError: undefined method `find_or_create_domain' for Domain>
#<NameError: uninitialized constant Domain>
#<NameError: uninitialized constant FileImporterWorker::Domain>
#<NameError: uninitialized constant Subscriber>
#<NameError: uninitialized constant FileImporterWorker::Subscriber>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'NSBundle' not found>
#<NameError: NameError>
#<NameError: NameError>
#<LoadError: C constant 'NSProxy' not found>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::CoreImageProcessor>
#<MissingSourceFile: no such file to load -- gd2>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::Gd2Processor>
#<MissingSourceFile: no such file to load -- mini_magick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::MiniMagickProcessor>
#<MissingSourceFile: no such file to load -- RMagick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::RmagickProcessor>
#<MissingSourceFile: no such file to load -- image_science>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::ImageScienceProcessor>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends::FileSystemBackend>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends>
#<NameError: uninitialized constant ImportedFile>
#<NameError: uninitialized constant FileImporterWorker::ImportedFile>
#<NameError: uninitialized constant FileImporterWorker>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:27:53 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:46:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `each'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:45:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<TypeError: can't convert nil into String>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: C constant 'RBRuntime' not found>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<TypeError: can't convert nil into String>
Fri Feb 13 00:33:37 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- sqlite3>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<ArgumentError: Unknown key(s): domain>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'RBRuntime' not found>
#<ArgumentError: Unknown key(s): domain>
#<NameError: uninitialized constant Domain>
#<NameError: uninitialized constant FileImporterWorker::Domain>
#<EOFError: end of file reached>
#<Errno::EEXIST: File exists - /Users/noelrocha/Workspace/rails/kadumo/imported_files/0000/0001>
#<LoadError: C constant 'NSBundle' not found>
#<NameError: NameError>
#<NameError: NameError>
#<LoadError: C constant 'NSProxy' not found>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::CoreImageProcessor>
#<MissingSourceFile: no such file to load -- gd2>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::Gd2Processor>
#<MissingSourceFile: no such file to load -- mini_magick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::MiniMagickProcessor>
#<MissingSourceFile: no such file to load -- RMagick>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::RmagickProcessor>
#<MissingSourceFile: no such file to load -- image_science>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors::ImageScienceProcessor>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Processors>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends::FileSystemBackend>
#<NameError: uninitialized constant Technoweenie::AttachmentFu::Backends>
#<NameError: uninitialized constant ImportedFile>
#<NameError: uninitialized constant FileImporterWorker::ImportedFile>
#<NameError: uninitialized constant FileImporterWorker>
#<MissingSourceFile: no such file to load -- sqlite3>
Fri Feb 13 00:38:12 -0200 2009
SIGTERM
["/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `sleep'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:57:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `loop'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:44:in `watch'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `fork'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/monitor.rb:111:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application_group.rb:113:in `create_monitor'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:244:in `start'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:139:in `run'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `catch_exceptions'", "/Library/Ruby/Gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:138:in `run'", "script/../lib/daemons/background_ctl:20"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<NameError: uninitialized constant FileImporterWorker::DbAlias>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ENOENT: No such file or directory - /Users/noelrocha/Workspace/rails/kadumo/log/background.rb.pid>
#<SystemExit: exit>
#<TypeError: can't convert nil into String>
#<NameError: uninitialized constant DbAlias>
#<NameError: uninitialized constant FileImporterWorker::DbAlias>
